<script setup lang="ts">
import {computed, ref} from 'vue'
const tabs=['Overview','Agents','Workflows','Marketplace','Knowledge','MCP & Tools','Approvals','Audit']
const tab=ref('Overview')
const agents=[['Project Agent','工程项目','运行中'],['BIM Agent','BIM/IFC','运行中'],['Water Agent','水务/SCADA','运行中'],['IoT Agent','IoT/MQTT','运行中']]
const workflows=[['项目进度自动审查','Project','event','READY'],['BIM 模型问题闭环','BIM','manual','READY'],['设备异常工单闭环','IoT','event','RUNNING']]
const packs=[['工程项目 Agent','MPP / Gantt / 进度'],['BIM Agent','IFC / Revit / 构件'],['水务 Agent','SCADA / 水质 / 曝气'],['IoT Agent','MQTT / TDengine / 告警']]
const selected=ref('Project Agent')
const metric= computed(()=>tab.value==='Overview'? 'Enterprise Agent OS':'管理 · '+tab.value)
</script>
<template><main><header><div><h1>YoungAgent</h1><p>Enterprise Agent OS · {{metric}}</p></div><div class="top"><span>Tenant: demo</span><span class="ok">● System Healthy</span><button>＋ New Agent</button></div></header><div class="layout"><aside><button v-for="t in tabs" :key="t" @click="tab=t" :class="{active:tab===t}">{{t}}</button><div class="sidebox"><b>Runtime</b><br>LLM Router <span>OK</span><br>MCP Gateway <span>OK</span><br>Event Bus <span>OK</span><br>Audit <span>ON</span></div></aside><section class="content"><template v-if="tab==='Overview'"><div class="hero"><div><small>ENTERPRISE AGENT OS</small><h2>让 Agent 真正完成企业业务闭环</h2><p>感知 → 推理 → 决策 → 审批 → 执行 → 验证 → 审计</p></div><div class="hero-badge">V5.0</div></div><div class="cards"><div><small>Active Agents</small><strong>12</strong><em>+4 domain agents</em></div><div><small>Running Workflows</small><strong>28</strong><em>7 event triggered</em></div><div><small>MCP / Tools</small><strong>46</strong><em>all tenant scoped</em></div><div><small>Pending Approval</small><strong>3</strong><em>human review required</em></div></div><div class="grid"><div class="panel"><h3>Domain Agents</h3><div v-for="a in agents" :key="a[0]" class="row" @click="selected=a[0]"><div><b>{{a[0]}}</b><small>{{a[1]}}</small></div><span class="pill">{{a[2]}}</span></div></div><div class="panel"><h3>Workflow Activity</h3><div v-for="w in workflows" :key="w[0]" class="row"><div><b>{{w[0]}}</b><small>{{w[1]}} · {{w[2]}}</small></div><span class="pill">{{w[3]}}</span></div></div></div></template><template v-else><div class="titlebar"><div><h2>{{tab}}</h2><p>统一管理 YoungAgent 的企业能力与运行状态。</p></div><button class="primary">＋ Create</button></div><div class="panel list" v-if="tab==='Marketplace'"><div v-for="p in packs" :key="p[0]" class="pack"><div><b>{{p[0]}}</b><small>{{p[1]}}</small></div><button>Installed</button></div></div><div class="panel" v-else><h3>{{tab}} Console</h3><p>此模块已连接 Agent Runtime / MCP / Workflow / Audit 数据接口。</p><div class="empty">Ready for production data</div></div></template></section></div></main></template>
<style>body{margin:0;background:#f5f7fb;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",system-ui;color:#172033}*{box-sizing:border-box}main{min-height:100vh}header{height:76px;background:#fff;border-bottom:1px solid #e7eaf0;padding:0 34px;display:flex;align-items:center;justify-content:space-between}h1{margin:0;font-size:22px}header p{margin:4px 0 0;color:#667085;font-size:12px}.top{display:flex;align-items:center;gap:18px;font-size:12px;color:#667085}.ok{color:#159957}.top button,.primary{border:0;background:#2563eb;color:white;border-radius:8px;padding:10px 15px}.layout{display:grid;grid-template-columns:235px 1fr;min-height:calc(100vh - 76px)}aside{background:#fff;border-right:1px solid #e7eaf0;padding:18px 12px}aside>button{width:100%;border:0;background:transparent;text-align:left;padding:11px 14px;border-radius:8px;color:#667085;cursor:pointer;margin-bottom:3px}aside>button.active{background:#edf3ff;color:#2563eb;font-weight:600}.sidebox{margin:30px 8px 0;padding:14px;border:1px solid #e7eaf0;border-radius:10px;font-size:12px;line-height:2.1;color:#667085}.sidebox span{float:right;color:#159957}.content{padding:28px 34px}.hero{background:linear-gradient(135deg,#101828,#243b73);color:#fff;border-radius:16px;padding:30px;display:flex;justify-content:space-between;align-items:center}.hero small{letter-spacing:1.5px;opacity:.7}.hero h2{font-size:28px;margin:10px 0}.hero p{opacity:.78}.hero-badge{font-size:30px;font-weight:700;padding:20px;border:1px solid #ffffff33;border-radius:14px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:16px 0}.cards>div,.panel{background:#fff;border:1px solid #e7eaf0;border-radius:13px;padding:18px}.cards small,.cards em,.row small,.pack small{display:block;color:#667085;font-size:11px}.cards strong{display:block;font-size:27px;margin:8px 0}.cards em{font-style:normal;color:#159957}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel h3{margin:0 0 12px}.row,.pack{display:flex;justify-content:space-between;align-items:center;padding:13px 0;border-bottom:1px solid #eef0f4;cursor:pointer}.row:last-child,.pack:last-child{border-bottom:0}.row b,.pack b{font-size:13px}.pill{font-size:10px;background:#eef8f1;color:#159957;border-radius:999px;padding:5px 8px}.titlebar{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.titlebar h2{margin:0}.titlebar p{color:#667085}.pack button{border:1px solid #d5dbe5;background:#f8fafc;border-radius:7px;padding:8px}.empty{margin-top:20px;border:1px dashed #cbd5e1;border-radius:10px;padding:70px;text-align:center;color:#98a2b3}@media(max-width:1000px){.cards{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:190px 1fr}.grid{grid-template-columns:1fr}}</style>
